pybo/views/answer_views.py
from flask import Flask,Blueprint,render_template,request,url_for,g,flash
from datetime import datetime
from pybo.models import Question,Answer
from pybo import db
from werkzeug.utils import redirect
from pybo.forms import AnswerForm
from pybo.views.auth_views import required_login

bp=Blueprint("answer",__name__,url_prefix="/answer")

@bp.route("/delete/<int:answer_id>")
@required_login
def delete(answer_id):
        answer=Answer.query.get_or_404(answer_id)
        question_id=answer.question.id

        if g.user !=answer.user:
                flash("삭제 권한이 없습니다.")
        else:
                db.session.delete(answer)
                db.session.commit()

        return redirect(url_for('question.detail',question_id=question_id))


@bp.route("/update/<int:answer_id>",methods=("GET","POST"))
@required_login
def update(answer_id):
        answer=Answer.query.get_or_404(answer_id)
        if g.user !=answer.user:
                flash("수정 권한이 없습니다.")
                return redirect(url_for('question.detail',question_id=answer.question.id))
        if request.method == "GET":
                form=AnswerForm(obj=answer)
        else:
                form=AnswerForm()
                if form.validate_on_submit():
                        form.populate_obj(answer)
                        answer.update_date=datetime.now()
                        db.session.commit()
                        return redirect(url_for('question.detail',question_id=answer.question.id))



        return render_template('answer/answer_form.html',form=form)


@bp.route('/create/<int:question_id>', methods=('POST', ))
@required_login
def create(question_id):
        
        form=AnswerForm()
        question = Question.query.get_or_404(question_id)
        if form.validate_on_submit():
                content = request.form['content'] 
                create_date = datetime.now()
                user_id=request.form["user_id"]
                answer = Answer(question=question, content=content, create_date=create_date,user_id=user_id)
                


                db.session.add(answer)
                db.session.commit()

                return redirect(url_for('question.detail', question_id=question_id))

        return render_template("question/question_detail.html",question=question,form=form)

pybo/views/question_views.py
from flask import Flask, Blueprint, render_template, request, url_for, g, flash
from pybo.models import Question
from pybo.forms import QuestionForm
from werkzeug.utils import redirect 
from datetime import datetime 
from pybo import db 
from pybo.forms import AnswerForm
import time
from pybo.views.auth_views import required_login
from pybo.views.test_views import extract_origin_name, make_new_name, makedirectory
import os

bp = Blueprint("question", __name__, url_prefix="/question")

@bp.route("/delete/<int:question_id>")
@required_login
def delete(question_id):
    question = Question.query.get_or_404(question_id)

    if g.user != question.user:
        flash("삭제 권한이 없습니다.")
        return redirect(url_for("question.detail", question_id=question_id))
    
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question.index'))

    


@bp.route("/update/<int:question_id>", methods=('GET', 'POST'))
@required_login
def update(question_id):
    question = Question.query.get_or_404(question_id)
    
    if g.user != question.user:
        flash("수정권한이 없습니다.")
        return redirect(url_for('question.detail', question_id=question_id))
    
    if request.method == "POST":
        form = QuestionForm()

        if form.validate_on_submit():

            form.populate_obj(question)
            question.update_date = datetime.now()

            del_img = request.form.get("del_img") #================================시작
            
            if del_img == "-1": 
                
                delete_filename = form.file_path.data

                if delete_filename:
                    delete_file_path = "pybo"+ delete_filename
                    os.remove(delete_file_path)

                question.file_path=""

                

            file = request.files["file"]
            
            if file.filename:
                delete_filename = form.file_path.data
                

                if delete_filename:
                    delete_file_path = "pybo"+ delete_filename
                    os.remove(delete_file_path)

                filename = file.filename
                filename = make_new_name(filename)
                upload_path = makedirectory()
                path = os.path.join(upload_path, filename)

                file.save(path)

                idx = path.find("/static/upload")
                file_path = path[idx:]

                question.file_path = file_path #================================끝         

            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))

    else:
        form = QuestionForm(obj=question)
        
    return render_template("question/question_update_form.html", form=form)


@bp.route("/create", methods=('GET', 'POST'))
@required_login
def create():
    form = QuestionForm()

    if request.method == 'POST' and form.validate_on_submit():
        subject = form.subject.data 
        content = form.content.data 
        create_date = datetime.now()
        user_id = form.user_id.data

        file = request.files["file"]
        filename = file.filename

        filename = make_new_name(filename)

        upload_path = makedirectory()

        path = os.path.join(upload_path, filename)
        path = path.replace("\\", "/")

        file.save(path)

        idx = path.find("/static/upload")

        file_path = path[idx:]


        question = Question(subject=subject, content=content,
                            create_date=create_date, user_id=user_id,
                            file_path=file_path)
        
        db.session.add(question)

        db.session.commit()
        return redirect(url_for("main.index"))

    return render_template("question/question_form.html", form=form)

@bp.route("/detail/<int:question_id>")
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get(question_id)
    return render_template("question/question_detail.html", 
                           question=question, form=form)

@bp.route("/list")
def index():
    page = request.args.get("page", type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page=page, per_page=10)

    return render_template("question/question_list.html", question_list =question_list )

pybo/templates/question/question_detail.html
{% extends 'base.html' %}

{% block content %}

{% include "weather_part.html" %}

{% if question %}
<div class="container my-3">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{question.subject}}</h5>

          
          <div>
            <img width="30%" height="30%" src="{{question.file_path}}" alt="첨부된 파일">
          </div>

          
          <p class="card-text">{{question.content}}</p>
          <div class="d-flex justify-content-end">
            {{question.user.username}} | 
            {{question.create_date | datetime}}
          </div>
          <a href="{{url_for('main.index')}}" class="card-link">목록</a>
          
          {% if g.user == question.user %}
          <a href="{{url_for('question.update',question_id=question.id)}}" class="card-link">수정</a>
          <a href="{{url_for('question.delete',question_id=question.id)}}" class="delete card-link">삭제</a> 
          {% endif %}

        </div>
    </div>

    <h4 class="border-bottom my-3 py-2">{{question.answer_set | length}} 개의 답글이 있음</h4>
    <div id="replies">
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
          <p class="card-text">{{answer.content}}</p>
          <div class="d-flex justify-content-end">
            {{answer.user.username}} |
            {{answer.create_date | datetime}}
          </div>
          {% if g.user == answer.user %}
          <a href="{{url_for('answer.update',answer_id=answer.id)}}" class="card-link">수정</a>
          <a href="{{url_for('answer.delete' ,answer_id=answer.id)}}" class="delete card-link">삭제</a>
          {% endif %}
        </div>
    </div>
    
    {% endfor %}
    </div>
</div> <!-- class = container 끝 -->




<form method="post" action="{{url_for('answer.create', question_id=question.id)}}">
  <!-- CSRF 토큰을 넣어 주세요 -->
  {{form.csrf_token}}

  <!-- 에러가 화면에 출력되게 하세요. -->
  {% if form.errors %}
    <div>
      {% for field, errors in form.errors.items() %}
        <p>{{form[field].label}}</p>
        {% for error in errors %}
          <p>{{error}}</p>
        {% endfor %}
      {% endfor %}
    </div>
  {% endif %}
    <input type="hidden" name="user_id" value="{{g.user.id}}"> <!--############-->
    
    
    <textarea class="form-content" {% if not g.user %}disabled{% endif %}  name="content" rows="10">{% if not g.user %}로그인 후 사용하세요.{% endif %}</textarea>
   <!--<textarea disabled name="content" rows="10">로그인후 사용하세요</textarea>-->
    <button class="my-3 btn btn-primary">답글 등록</button>
</form>
{% else %}
<p>데이터가 없습니다.</p>
{% endif %}
{% endblock %}


{% block script %}
<script>
$(document).ready(function(){
  getWeather();
  $(".delete").click(function(event){
    event.preventDefault()
    console.log("zzzzzzzzzz");
    let areyousure =confirm("정말로 삭제할래요?")
    
    if(areyousure){
      location.href=$(this).attr("href")
    }
  });
});
</script>




{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}

{% block content %}
<h4>질문 {{'수정' if g.is_update else '등록'}} 화면</h4>

<form method="post" class="my-4" enctype="multipart/form-data">
  {{form.csrf_token}}

  {% include "form_errors.html" %}
  
  <input type="hidden" name="user_id" value="{{g.user.id}}">
 


  
 
    <div  class= "my-3">
      <label for="subject" class="form-label">제목</label>
      <input class="form-control" id="subject" name="subject" value="{{form.subject.data or ''}}">
      
    </div>

    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-content" name="content" id="content" rows="10"  >{{form.content.data or ''}}</textarea>

   
    </div>
    <div  class= "my-3">
      <label for="file" class="form-label">첨부파일</label>
      <input type="file" class="form-control" id="file" name="file" value="{{form.file_path.data or ''}}">
      
    </div>
    <button type="submit" class="btn btn-primary">{{'수정' if g.is_update else '등록'}}</button>
  </form>

{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html'%}

{% block content %}
<body>
{% if question_list %}
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">번호</th>
                <th scope="col">제목</th>
                <th scope="col">작성자</th>
                <th scope="col">작성일</th>

            </tr>
            </thead>
            <tbody>
                {% for question in question_list %}
            <tr>
                <td>{{(question_list.page -1)*question_list.per_page + loop.index}}</td>
                <td>
                    <a href="{{url_for('question.detail',question_id=question.id)}}">
                        {{question.subject}}
                        {% if question.answer_set|length > 0 %}
                        <span>[{{question.answer_set|length}}]</span>
                        {% endif %}
                    </a>
                </td>
                <td>
                    {{question.user.username}}
                </td>
                <td>{{question.create_date|datetime}}</td>
            </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>


   {% include "paging_part.html" %}

    <a href="{{url_for('question.create')}}">질문등록</a>

    {% else %}
    <p>데이터가 없습니다.</p>
    {% endif %}
    <select name="test" id="test">
        <option value="hello1">hello1</option>
        <option value="hello2">hello2</option>
        <option value="hello3">hello2</option>
    </select>
    {% include "weather_part.html" %}
    <div id="show_weather">
        <div>
            <span>강수형태</span>:
            <span id="PTY"></span>
        </div>
        <div>
            <span>기온</span>
            <span id="T1H"></span><span>도</span>

        </div>

        <div>
            <span>습도</span>
            <span id="REH"></span><span>%</span>

        </div>
        <div>
            <span>시간당 강수량</span>
            <span id="RN1"></span> <span>mm</span>

        </div>
        <div>
            <span>풍향</span>
            <span id="VEC"></span>
        </div>
        <div>
            <span>풍속</span>
            <span id="WSD"></span> <span>m/s</span>

        </div>
    </div>
    <input type="hidden" id="city" value="/서울 강동구 천호제1동">

{% endblock %}
    
{% block script %}
<script>
$(document).ready(function(){
    getWeather();
})

</script>
    
{% endblock %}

pybo/templates/question/question_update_form.html
{% extends 'base.html' %}

{% block content %}
<h4>질문 수정 화면</h4>

<form method="post" class="my-4" enctype="multipart/form-data">
  {{form.csrf_token}}
  <!--#============================================-->
  <input type="hidden" name="file_path" id="{{form.file_path.data or ''}}">
  <input type="hidden" name="del_img" value="1" >
  
  
  {% include "form_errors.html" %}
   
  <input type="hidden" name="user_id" value="{{g.user.id}}">
 
 
    <div  class= "mb-3">
      <label for="subject" class="form-label">제목</label>
      <input class="form-control" id="subject" name="subject" value="{{form.subject.data or ''}}">
    </div>
    

    <div  class= "mb-3">
      <label for="file" class="form-label">첨부파일</label>
      <input type="file" class="form-control" id="file" name="file">
    </div>

    <div class= "mb-3">
      <img width="30%" height="30%" src="{{form.file_path.data or ''}}" alt="첨부된 파일">
      <button type="button" id="btn_del_attach">첨부파일 삭제</button>
    </div>



    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10" >{{form.content.data or ''}}</textarea>

   
    </div>
    
    <button type="submit" class="btn btn-primary">등록</button>
  </form>

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
  $("#btn_del_attach").click(function(){
    $('[name="del_img"]').val(-1)
    $('[alt="첨부된 파일"]').prev().remove();

  });
});
</script>
{% endblock %}