pybo/views/auth_views.py
from flask import Flask, Blueprint, url_for, render_template, request,flash,session, g
from werkzeug.utils import redirect
from pybo import db
from pybo.forms import UserCreateForm,UserLoginForm
from pybo.models import User
from werkzeug.security import generate_password_hash,check_password_hash
import functools

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/checkusername/<username>")
def check_user_name(username):
    user=User.query.filter_by(username=username).first()

    if not user:
        return str(1);
    else: 
        return str(-1);



    



@bp.route("/checkid/<username>")
def checkid(username):
    print(request.args.get("name"))
    print(request)

    return id+": test"


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("main.index"))



@bp.route("/login",methods=("GET","POST"))
def login():
    form=UserLoginForm()

    if request.method == "POST" and form.validate_on_submit():
        error=None

        user=User.query.filter_by(username=form.username.data).first()
        if not user:
            error=" 존재하지 않는 회원입니다. "
        elif not check_password_hash(user.password, form.password.data):
            error="비밀번호가 틀렸습니다."

        if error is None:
            session.clear()
            session['user_id']=user.id

            to = request.args.get("to","")
            if to:
                return redirect(to)
            else:
                return redirect(url_for("main.index"))

        flash(error)

    return render_template("auth/login.html",form=form)

@bp.route("/signup", methods=("GET", "POST" ))
def signup():
    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit(): # ========= db 저장 작업 시작
        user = User.query.filter_by(username=form.username.data).first()
        user2 = User.query.filter_by(email=form.email.data).first()

        if user2:
            flash("이미 존재하는 이메일입니다.")
            return render_template("auth/signup.html",form=form)
        
        if not user: # ================ db에 입력받은 username에 해당하는 회원이 없을 경우
            username = form.username.data
            password = generate_password_hash(form.password1.data)
            email = form.email.data

            user = User(username=username, password=password, email=email)
            
            db.session.add(user)
            db.session.commit()


            return redirect(url_for("main.index"))
        else:
            flash("이미 존재하는 사용자입니다.")

    return render_template("auth/signup.html", form=form)

def required_login(func):
    @functools.wraps(func)
    def wrapper(*args,**kwargs):
        if g.user is None:
            to = request.url if request.method=="GET" else ''
            return redirect(url_for('auth.login',to=to))
        

        return func(*args,**kwargs)
    return wrapper

pybo/views/weather_views.py
from flask import Flask,Blueprint,render_template
import pandas as pd
import requests
import json
import math


bp=Blueprint("weather",__name__,url_prefix="/weather")
df= pd.read_excel("pybo\static\others\단기예보_위경도.xlsx")
df1=df.copy()

df2=df1.drop(df1.columns[7:-3],axis="columns")
df3=df2.drop(df2.columns[[0,-1]],axis="columns")
df3=df3.rename(columns={"격자 X":"X","격자 Y":"Y","경도(초/100)":"경도","위도(초/100)":"위도"})


@bp.route("/item/<date>/<address>")
def get_weather_item(date,address):
    global df3
    url = f'http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst'
    api="9mjKP5z2Q7D8AUC7p%2BQGHXKGAYVume2u6E6SLKF4deV6pXX9Ve7EnZ64LeGms0VH4Zu12h7R8t673SqcZO9%2BIA%3D%3D"
    
    df3_result=get_xy(address)

    nx=df3_result[0]
    ny=df3_result[1]

    url = f'{url}?serviceKey={api}&numOfRows=1000&dataType=JSON&base_date={date}&base_time=0600&nx={nx}&ny={ny}'
    
    response = requests.get(url)
    json_bytes=response.content
    json_str=json_bytes.decode("utf-8")
    weather=json.loads(json_str)

    item=weather["response"]["body"]["items"]["item"]
    return item



def get_xy(address):
    global df3
    arr=address.split(sep=" ")
    size=len(arr)
    arr[0]=change_city_name(arr[0])
        
    cond1=df3["1단계"].str.contains(arr[0])
    
    val=""
    
    if size == 1:
        cond2_na=df2["2단계"].isnull()
        cond3_na=df2["3단계"].isnull()
        
        val= df3.loc[cond1 & cond2_na & cond3_na]
        
    elif size==2:
        cond2=df3["2단계"].str.contains(arr[1])
        cond3_na=df2["3단계"].isnull()
        
        val= df3.loc[cond1 & cond2 & cond3_na]
        
    elif size==3:
        cond2=df3["2단계"].str.contains(arr[1])
        cond3=df2["3단계"].str.contains(arr[2])
        
        val= df3.loc[cond1 & cond2 & cond3]
        
    idx=val.index.tolist()[0]    
    return val.loc[idx,"X"],val.loc[idx,"Y"]

def change_city_name(city):
    dic1={
        "경기":"경기도",
        "서울":"서울특별시",
        "충남":"충청남도",
        "충북":"충청북도",
        "전남":"전라남도",
        "전북":"전라북도",
        "경남":"경상남도",
        "경북":"경상북도",
        "부산":"부산광역시",
        "강원":"강원특별자치도",
        "인천":"인천광역시",
        "대구":"대구광역시",
        "대전":"대전광역시",
        "울산":"울산광역시",
        "제주":"제주특별자치도",
        "세종":"세종특별자치시"
    }
    try:
        return dic1[city]
    except KeyError as e:
        return city

pybo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>
     <script crc="{{url_for('static',filename='/static/js/weather.js')}}"></script>
  </head>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('main.index')}}">MBC606</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          {% if g.user  %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.logout')}}">로그아웃</a>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('auth.signup')}}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}" target="_blank">로그인</a>
            </li>
          {% endif %}
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


    <div class="container my-3">
        {% block content %}
        


        
        {% endblock %}
    </div>
    {% block script %}
   
    {% endblock %}


</html>

pybo/templates/child.html
{% extends '/test/parent.html' %}

{% block content %}
<div>zzzzz</div>
{% endblock %}

pybo/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}    
        <p>{{form[field].label}}</p>
            <ul>
                {% for error in errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
    {% endfor %}
</div>
{% endif %}

{% for msg in get_flashed_messages() %}
<div class="alert alert-danger" role="alert"></div>
    {{msg}}
</div>
{% endfor %}

pybo/templates/paging_part.html
<nav aria-label="Page navigation example">
    <ul class="pagination justif-content-center">
        {% if question_list.has_prev %}
      <li class="page-item"><a class="page-link" href="{{url_for('question.index', page =question_list.prev_num)}}">이전</a></li>
      {% else %}
      
      {% endif %}

      {%for page in question_list.iter_pages() %}
        {% if page %}
        <li class="page-item{{'active'if page == question_list.page else ''}}"><a class="page-link" href="{{url_for('question.index', page=page)}}">{{page}}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
        {% endif %}
      {% endfor %}

      
      {% if question_list.has_next %}          
      <li class="page-item"><a class="page-link" href="{{url_for('question.index', page=question_list.next_num)}}">다음</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="javascript:void(0)">다음</a></li>
      {% endif %}
    </ul>
  </nav>

pybo/templates/parent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>hello</p>
    <p>world</p>

    {% block content %} <!--자식 html만이 갖고 있을 내용이 들어가는 부분-->
    {% endblock %}

    <div>end</div>


</body>
</html>

pybo/templates/weather.html
<div id="show_weather">
    <div>
        <span>강수형태</span>:
        <span id="PTY"></span>
    </div>
    <div>
        <span>기온</span>
        <span id="T1H"></span><span>도</span>

    </div>

    <div>
        <span>습도</span>
        <span id="REH"></span><span>%</span>

    </div>
    <div>
        <span>시간당 강수량</span>
        <span id="RN1"></span> <span>mm</span>

    </div>
    <div>
        <span>풍향</span>
        <span id="VEC"></span>
    </div>
    <div>
        <span>풍속</span>
        <span id="WSD"></span> <span>m/s</span>

    </div>
</div>